version: "3"

tasks:
  dev:
    cmds:
      - air
  docs:
    cmds:
      - swag init --dir ./cmd/server,./internal/todo
  build:
    cmds:
      - go build -o server cmd/server/main.go
  start:
    cmds:
      - ./server
  install:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/go-task/task/v3/cmd/task@latest
