basePath: /
definitions:
  category_entity.Category:
    properties:
      created_at:
        type: integer
      description:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
    type: object
  category_http.createCategoryRequest:
    properties:
      description:
        maxLength: 300
        type: string
      name:
        maxLength: 50
        minLength: 1
        type: string
    required:
    - name
    type: object
info:
  contact:
    name: Dhaniel Sales
  description: A simple Golang backend scaffold
  license:
    name: MIT
  title: Golang scaffold
  version: "1.0"
paths:
  /category:
    get:
      consumes:
      - '*/*'
      description: fetch every category available.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/category_entity.Category'
            type: array
      summary: Get all categories.
      tags:
      - Category
    post:
      consumes:
      - '*/*'
      description: creates one category.
      parameters:
      - description: Category to create
        in: body
        name: Category
        required: true
        schema:
          $ref: '#/definitions/category_http.createCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create one category.
      tags:
      - Category
swagger: "2.0"
