basePath: /
definitions:
  entity.Category:
    properties:
      created_at:
        type: integer
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
      products:
        items:
          $ref: '#/definitions/entity.Product'
        type: array
      slug:
        type: string
      updated_at:
        type: integer
    type: object
  entity.NoDb:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  entity.Product:
    properties:
      category_id:
        type: string
      created_at:
        type: integer
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      slug:
        type: string
      updated_at:
        type: integer
    type: object
  http.createCategoryRequest:
    properties:
      description:
        maxLength: 300
        minLength: 1
        type: string
      imageUrl:
        type: string
      name:
        maxLength: 50
        minLength: 1
        type: string
    required:
    - imageUrl
    - name
    type: object
  http.createProductRequest:
    properties:
      category_id:
        type: string
      description:
        maxLength: 300
        minLength: 1
        type: string
      name:
        maxLength: 50
        minLength: 1
        type: string
      price:
        minimum: 0
        type: number
    required:
    - category_id
    - name
    - price
    type: object
  http.updateCategoryRequest:
    properties:
      description:
        maxLength: 300
        minLength: 1
        type: string
      name:
        maxLength: 50
        minLength: 1
        type: string
    required:
    - name
    type: object
  http.updateProductRequest:
    properties:
      description:
        maxLength: 300
        minLength: 1
        type: string
      name:
        maxLength: 50
        minLength: 1
        type: string
    required:
    - name
    type: object
info:
  contact:
    name: Dhaniel Sales
  description: A simple API to show how to use Go in a clean way
  title: Go Scaffold API
  version: "1.0"
paths:
  /api/v0/category:
    get:
      consumes:
      - '*/*'
      description: fetch every category available.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Category'
            type: array
      summary: Get all categories.
      tags:
      - Category
    post:
      consumes:
      - '*/*'
      description: creates one category.
      parameters:
      - description: Category to create
        in: body
        name: Category
        required: true
        schema:
          $ref: '#/definitions/http.createCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: integer
      summary: Create one category.
      tags:
      - Category
  /api/v0/category/{id}:
    delete:
      consumes:
      - '*/*'
      description: deletes one category by id.
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Delete one category.
      tags:
      - Category
    get:
      consumes:
      - '*/*'
      description: fetch one category by id.
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Category'
      summary: Get one category.
      tags:
      - Category
    put:
      consumes:
      - '*/*'
      description: updates one category by id.
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: Category to update
        in: body
        name: Category
        required: true
        schema:
          $ref: '#/definitions/http.updateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Update one category.
      tags:
      - Category
  /api/v0/no-db:
    get:
      consumes:
      - '*/*'
      description: get many fake data.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.NoDb'
            type: array
      summary: Get many fake data.
      tags:
      - NoDb
  /api/v0/product:
    get:
      consumes:
      - '*/*'
      description: fetch every product available.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Product'
            type: array
      summary: Get all categories.
      tags:
      - Product
    post:
      consumes:
      - '*/*'
      description: creates one product.
      parameters:
      - description: Product to create
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/http.createProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: integer
      summary: Create one product.
      tags:
      - Product
  /api/v0/product/{id}:
    delete:
      consumes:
      - '*/*'
      description: deletes one product by id.
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Delete one product.
      tags:
      - Product
    get:
      consumes:
      - '*/*'
      description: fetch one product by id.
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Product'
      summary: Get one product.
      tags:
      - Product
    put:
      consumes:
      - '*/*'
      description: updates one product by id.
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Product to update
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/http.updateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Update one product.
      tags:
      - Product
swagger: "2.0"
